#!/usr/bin/env python3
"""
Generate synonym/antonym data for the Ring Bell game.
Produces src/data/synonym_antonym.json
Structure: { "字/词": { "synonyms": ["同义词1", ...], "antonyms": ["反义词1", ...] } }
"""

import json
import os

# ============================================================
# 手工整理的同义词/反义词数据集
# 每个条目：词语 -> { synonyms: [...], antonyms: [...] }
# ============================================================

raw_data = {
    # === 形容词 - 大小长短 ===
    "大": {"synonyms": ["巨", "庞", "硕", "宏"], "antonyms": ["小", "微", "细"]},
    "小": {"synonyms": ["微", "细", "渺"], "antonyms": ["大", "巨", "宏"]},
    "巨": {"synonyms": ["大", "庞", "硕"], "antonyms": ["小", "微"]},
    "长": {"synonyms": ["久", "远"], "antonyms": ["短"]},
    "短": {"synonyms": ["促"], "antonyms": ["长"]},
    "高": {"synonyms": ["耸", "峻"], "antonyms": ["低", "矮"]},
    "低": {"synonyms": ["矮"], "antonyms": ["高"]},
    "矮": {"synonyms": ["低"], "antonyms": ["高", "长"]},
    "深": {"synonyms": ["厚"], "antonyms": ["浅"]},
    "浅": {"synonyms": ["薄"], "antonyms": ["深", "厚"]},
    "厚": {"synonyms": ["深", "重"], "antonyms": ["薄", "浅"]},
    "薄": {"synonyms": ["浅"], "antonyms": ["厚", "深"]},
    "宽": {"synonyms": ["阔", "广"], "antonyms": ["窄"]},
    "窄": {"synonyms": ["狭"], "antonyms": ["宽", "阔", "广"]},
    "广": {"synonyms": ["宽", "阔", "泛"], "antonyms": ["窄", "狭"]},
    "阔": {"synonyms": ["宽", "广"], "antonyms": ["窄", "狭"]},
    "粗": {"synonyms": ["壮"], "antonyms": ["细"]},
    "细": {"synonyms": ["微"], "antonyms": ["粗", "大"]},
    "远": {"synonyms": ["遥", "辽"], "antonyms": ["近"]},
    "近": {"synonyms": ["邻", "旁"], "antonyms": ["远", "遥"]},
    "遥": {"synonyms": ["远"], "antonyms": ["近"]},
    "多": {"synonyms": ["众", "繁", "丰"], "antonyms": ["少", "寡"]},
    "少": {"synonyms": ["寡", "稀"], "antonyms": ["多", "众", "丰"]},
    "众": {"synonyms": ["多", "群"], "antonyms": ["少", "寡"]},
    "寡": {"synonyms": ["少", "稀"], "antonyms": ["多", "众"]},
    "重": {"synonyms": ["沉", "吨"], "antonyms": ["轻"]},
    "轻": {"synonyms": ["浮"], "antonyms": ["重", "沉"]},
    "沉": {"synonyms": ["重"], "antonyms": ["轻"]},
    "快": {"synonyms": ["速", "迅", "疾"], "antonyms": ["慢"]},
    "慢": {"synonyms": ["缓", "迟"], "antonyms": ["快", "速"]},
    "速": {"synonyms": ["快", "迅"], "antonyms": ["慢", "缓"]},
    "迟": {"synonyms": ["慢", "晚"], "antonyms": ["早", "快"]},
    "早": {"synonyms": ["先", "初"], "antonyms": ["晚", "迟"]},
    "晚": {"synonyms": ["迟", "暮"], "antonyms": ["早", "先"]},
    "新": {"synonyms": ["鲜", "初"], "antonyms": ["旧", "老"]},
    "旧": {"synonyms": ["老", "陈"], "antonyms": ["新", "鲜"]},
    "老": {"synonyms": ["旧", "陈"], "antonyms": ["新", "少"]},
    "鲜": {"synonyms": ["新"], "antonyms": ["旧", "陈"]},
    "陈": {"synonyms": ["旧", "老"], "antonyms": ["新", "鲜"]},
    "好": {"synonyms": ["佳", "优", "良"], "antonyms": ["坏", "差", "劣"]},
    "坏": {"synonyms": ["差", "劣", "恶"], "antonyms": ["好", "佳", "优"]},
    "优": {"synonyms": ["好", "佳", "良"], "antonyms": ["差", "劣"]},
    "劣": {"synonyms": ["差", "坏"], "antonyms": ["优", "好"]},
    "差": {"synonyms": ["劣", "坏"], "antonyms": ["好", "优"]},
    "佳": {"synonyms": ["好", "优"], "antonyms": ["差", "劣"]},
    "良": {"synonyms": ["好", "优"], "antonyms": ["差", "劣"]},
    "美": {"synonyms": ["丽", "秀"], "antonyms": ["丑"]},
    "丑": {"synonyms": ["陋"], "antonyms": ["美", "丽"]},
    "丽": {"synonyms": ["美", "秀"], "antonyms": ["丑"]},
    "秀": {"synonyms": ["美", "丽"], "antonyms": ["丑", "陋"]},
    "亮": {"synonyms": ["明", "光"], "antonyms": ["暗", "黑"]},
    "暗": {"synonyms": ["黑", "昏"], "antonyms": ["亮", "明"]},
    "明": {"synonyms": ["亮", "光"], "antonyms": ["暗", "黑"]},
    "黑": {"synonyms": ["暗", "昏"], "antonyms": ["白", "明"]},
    "白": {"synonyms": ["素"], "antonyms": ["黑"]},
    "昏": {"synonyms": ["暗"], "antonyms": ["明", "亮"]},
    "冷": {"synonyms": ["寒", "凉"], "antonyms": ["热", "暖"]},
    "热": {"synonyms": ["暖", "烫"], "antonyms": ["冷", "寒"]},
    "寒": {"synonyms": ["冷", "凉"], "antonyms": ["热", "暖"]},
    "暖": {"synonyms": ["热", "温"], "antonyms": ["冷", "寒"]},
    "凉": {"synonyms": ["冷", "寒"], "antonyms": ["热", "暖"]},
    "温": {"synonyms": ["暖"], "antonyms": ["冷", "寒"]},
    "硬": {"synonyms": ["坚", "刚"], "antonyms": ["软"]},
    "软": {"synonyms": ["柔", "绵"], "antonyms": ["硬", "坚"]},
    "坚": {"synonyms": ["硬", "刚"], "antonyms": ["软", "柔"]},
    "柔": {"synonyms": ["软", "绵"], "antonyms": ["硬", "刚"]},
    "刚": {"synonyms": ["硬", "坚"], "antonyms": ["软", "柔"]},
    "甜": {"synonyms": ["甘"], "antonyms": ["苦", "酸"]},
    "苦": {"synonyms": ["涩"], "antonyms": ["甜", "甘"]},
    "酸": {"synonyms": ["涩"], "antonyms": ["甜", "甘"]},
    "辣": {"synonyms": ["辛"], "antonyms": ["淡"]},
    "咸": {"synonyms": ["盐"], "antonyms": ["淡"]},
    "淡": {"synonyms": ["素"], "antonyms": ["浓", "咸", "辣"]},
    "浓": {"synonyms": ["稠", "厚"], "antonyms": ["淡", "稀"]},
    "稀": {"synonyms": ["淡"], "antonyms": ["浓", "稠"]},
    "稠": {"synonyms": ["浓"], "antonyms": ["稀", "淡"]},
    "干": {"synonyms": ["燥"], "antonyms": ["湿"]},
    "湿": {"synonyms": ["潮"], "antonyms": ["干", "燥"]},
    "燥": {"synonyms": ["干"], "antonyms": ["湿", "潮"]},
    "潮": {"synonyms": ["湿"], "antonyms": ["干", "燥"]},
    "净": {"synonyms": ["洁", "清"], "antonyms": ["脏"]},
    "脏": {"synonyms": ["污"], "antonyms": ["净", "洁", "清"]},
    "洁": {"synonyms": ["净", "清"], "antonyms": ["脏", "污"]},
    "清": {"synonyms": ["净", "洁"], "antonyms": ["浊", "脏"]},
    "浊": {"synonyms": ["浑"], "antonyms": ["清", "净"]},
    "浑": {"synonyms": ["浊"], "antonyms": ["清"]},
    "真": {"synonyms": ["实", "诚"], "antonyms": ["假", "伪"]},
    "假": {"synonyms": ["伪", "虚"], "antonyms": ["真", "实"]},
    "实": {"synonyms": ["真", "诚"], "antonyms": ["假", "虚"]},
    "虚": {"synonyms": ["假", "伪"], "antonyms": ["真", "实"]},
    "伪": {"synonyms": ["假", "虚"], "antonyms": ["真", "实"]},
    "诚": {"synonyms": ["真", "信"], "antonyms": ["假", "伪"]},
    "善": {"synonyms": ["良", "慈"], "antonyms": ["恶"]},
    "恶": {"synonyms": ["坏", "凶"], "antonyms": ["善", "良"]},
    "慈": {"synonyms": ["善", "仁"], "antonyms": ["恶", "凶"]},
    "凶": {"synonyms": ["恶", "狠"], "antonyms": ["善", "慈"]},
    "狠": {"synonyms": ["凶"], "antonyms": ["慈", "善"]},
    "仁": {"synonyms": ["慈", "善"], "antonyms": ["恶", "凶"]},
    "贵": {"synonyms": ["昂"], "antonyms": ["贱", "廉"]},
    "贱": {"synonyms": ["廉"], "antonyms": ["贵", "昂"]},
    "廉": {"synonyms": ["贱", "低"], "antonyms": ["贵", "昂"]},
    "昂": {"synonyms": ["贵"], "antonyms": ["廉", "贱"]},
    "富": {"synonyms": ["裕", "阔"], "antonyms": ["穷", "贫"]},
    "穷": {"synonyms": ["贫", "困"], "antonyms": ["富", "裕"]},
    "贫": {"synonyms": ["穷", "困"], "antonyms": ["富", "裕"]},
    "裕": {"synonyms": ["富"], "antonyms": ["穷", "贫"]},
    "困": {"synonyms": ["穷", "贫"], "antonyms": ["富", "裕"]},
    "强": {"synonyms": ["壮", "猛"], "antonyms": ["弱"]},
    "弱": {"synonyms": ["柔", "软"], "antonyms": ["强", "壮"]},
    "壮": {"synonyms": ["强", "健"], "antonyms": ["弱", "瘦"]},
    "健": {"synonyms": ["壮", "康"], "antonyms": ["弱", "病"]},
    "瘦": {"synonyms": ["细", "弱"], "antonyms": ["胖", "壮"]},
    "胖": {"synonyms": ["肥"], "antonyms": ["瘦"]},
    "肥": {"synonyms": ["胖"], "antonyms": ["瘦"]},
    "猛": {"synonyms": ["强", "烈"], "antonyms": ["弱", "柔"]},
    "烈": {"synonyms": ["猛", "强"], "antonyms": ["弱", "柔"]},
    "闲": {"synonyms": ["空", "暇"], "antonyms": ["忙", "碌"]},
    "忙": {"synonyms": ["碌"], "antonyms": ["闲", "暇"]},
    "碌": {"synonyms": ["忙"], "antonyms": ["闲", "空"]},
    "暇": {"synonyms": ["闲", "空"], "antonyms": ["忙", "碌"]},
    "静": {"synonyms": ["宁", "寂"], "antonyms": ["动", "闹"]},
    "动": {"synonyms": ["移", "行"], "antonyms": ["静", "止"]},
    "闹": {"synonyms": ["喧", "吵"], "antonyms": ["静", "宁"]},
    "宁": {"synonyms": ["静", "安"], "antonyms": ["闹", "吵"]},
    "安": {"synonyms": ["宁", "平"], "antonyms": ["危", "乱"]},
    "危": {"synonyms": ["险"], "antonyms": ["安", "稳"]},
    "险": {"synonyms": ["危"], "antonyms": ["安", "稳"]},
    "稳": {"synonyms": ["安", "固"], "antonyms": ["危", "险"]},
    "乱": {"synonyms": ["杂", "混"], "antonyms": ["治", "整"]},
    "治": {"synonyms": ["理", "管"], "antonyms": ["乱"]},
    "整": {"synonyms": ["齐", "全"], "antonyms": ["乱", "散"]},
    "齐": {"synonyms": ["整", "全"], "antonyms": ["乱", "散"]},
    "散": {"synonyms": ["乱"], "antonyms": ["整", "齐", "聚"]},
    "聚": {"synonyms": ["集", "合"], "antonyms": ["散", "分"]},
    "分": {"synonyms": ["离", "拆"], "antonyms": ["合", "聚"]},
    "合": {"synonyms": ["聚", "集"], "antonyms": ["分", "离"]},
    "离": {"synonyms": ["分", "别"], "antonyms": ["合", "聚"]},
    "别": {"synonyms": ["离", "分"], "antonyms": ["合", "聚"]},
    "集": {"synonyms": ["聚", "合"], "antonyms": ["散", "分"]},
    "喧": {"synonyms": ["闹", "吵"], "antonyms": ["静", "宁"]},
    "吵": {"synonyms": ["闹", "喧"], "antonyms": ["静", "宁"]},
    "寂": {"synonyms": ["静", "寞"], "antonyms": ["闹", "喧"]},
    "愁": {"synonyms": ["忧", "烦"], "antonyms": ["欢", "乐"]},
    "忧": {"synonyms": ["愁", "虑"], "antonyms": ["喜", "乐"]},
    "喜": {"synonyms": ["欢", "乐"], "antonyms": ["忧", "愁", "悲"]},
    "悲": {"synonyms": ["哀", "痛"], "antonyms": ["喜", "欢", "乐"]},
    "哀": {"synonyms": ["悲", "痛"], "antonyms": ["喜", "乐"]},
    "痛": {"synonyms": ["疼", "苦"], "antonyms": ["乐", "快"]},
    "欢": {"synonyms": ["喜", "乐"], "antonyms": ["悲", "愁"]},
    "乐": {"synonyms": ["喜", "欢"], "antonyms": ["悲", "忧", "愁"]},
    "怒": {"synonyms": ["气", "愤"], "antonyms": ["喜", "乐"]},
    "愤": {"synonyms": ["怒", "气"], "antonyms": ["平", "静"]},
    "急": {"synonyms": ["忙", "迫"], "antonyms": ["缓", "慢"]},
    "缓": {"synonyms": ["慢", "迟"], "antonyms": ["急", "快"]},
    "迫": {"synonyms": ["急", "紧"], "antonyms": ["缓", "松"]},
    "紧": {"synonyms": ["迫", "密"], "antonyms": ["松", "缓"]},
    "松": {"synonyms": ["缓", "宽"], "antonyms": ["紧", "密"]},
    "密": {"synonyms": ["紧", "稠"], "antonyms": ["松", "稀"]},
    "顺": {"synonyms": ["利", "畅"], "antonyms": ["逆", "阻"]},
    "逆": {"synonyms": ["反", "倒"], "antonyms": ["顺", "正"]},
    "正": {"synonyms": ["直", "端"], "antonyms": ["歪", "邪"]},
    "歪": {"synonyms": ["斜", "偏"], "antonyms": ["正", "直"]},
    "直": {"synonyms": ["正", "挺"], "antonyms": ["弯", "曲"]},
    "弯": {"synonyms": ["曲"], "antonyms": ["直"]},
    "曲": {"synonyms": ["弯"], "antonyms": ["直"]},
    "偏": {"synonyms": ["歪", "斜"], "antonyms": ["正", "中"]},
    "斜": {"synonyms": ["歪", "偏"], "antonyms": ["正", "直"]},
    "平": {"synonyms": ["坦", "均"], "antonyms": ["陡", "崎"]},
    "陡": {"synonyms": ["峭"], "antonyms": ["平", "坦"]},
    "坦": {"synonyms": ["平"], "antonyms": ["陡", "崎"]},
    "崎": {"synonyms": ["岖"], "antonyms": ["平", "坦"]},
    "满": {"synonyms": ["盈", "充"], "antonyms": ["空", "缺"]},
    "空": {"synonyms": ["虚"], "antonyms": ["满", "实"]},
    "盈": {"synonyms": ["满", "溢"], "antonyms": ["空", "缺"]},
    "缺": {"synonyms": ["少", "乏"], "antonyms": ["满", "全"]},
    "全": {"synonyms": ["整", "齐"], "antonyms": ["缺", "残"]},
    "残": {"synonyms": ["破", "缺"], "antonyms": ["全", "整"]},
    "破": {"synonyms": ["碎", "裂"], "antonyms": ["整", "完"]},
    "碎": {"synonyms": ["破"], "antonyms": ["整"]},
    "完": {"synonyms": ["整", "全"], "antonyms": ["缺", "残"]},
    "整": {"synonyms": ["完", "全"], "antonyms": ["破", "碎"]},
    "升": {"synonyms": ["上", "涨"], "antonyms": ["降", "落"]},
    "降": {"synonyms": ["落", "下"], "antonyms": ["升", "上"]},
    "落": {"synonyms": ["降", "下"], "antonyms": ["升", "上"]},
    "涨": {"synonyms": ["升", "增"], "antonyms": ["降", "减"]},
    "增": {"synonyms": ["加", "添"], "antonyms": ["减", "少"]},
    "减": {"synonyms": ["少", "降"], "antonyms": ["增", "加"]},
    "加": {"synonyms": ["增", "添"], "antonyms": ["减", "去"]},
    "去": {"synonyms": ["除", "减"], "antonyms": ["加", "添"]},
    "添": {"synonyms": ["加", "增"], "antonyms": ["减", "去"]},
    "存": {"synonyms": ["留", "保"], "antonyms": ["取", "消"]},
    "取": {"synonyms": ["拿", "得"], "antonyms": ["存", "留"]},
    "留": {"synonyms": ["存", "保"], "antonyms": ["去", "走"]},
    "保": {"synonyms": ["存", "守"], "antonyms": ["失", "丢"]},
    "失": {"synonyms": ["丢", "丧"], "antonyms": ["得", "获"]},
    "得": {"synonyms": ["获", "取"], "antonyms": ["失", "丢"]},
    "获": {"synonyms": ["得", "取"], "antonyms": ["失", "丧"]},
    "丢": {"synonyms": ["失", "掉"], "antonyms": ["得", "获"]},
    "掉": {"synonyms": ["丢", "落"], "antonyms": ["捡", "拾"]},
    "捡": {"synonyms": ["拾"], "antonyms": ["丢", "掉"]},
    "拾": {"synonyms": ["捡"], "antonyms": ["丢", "掉"]},

    # === 动词 - 行为动作 ===
    "来": {"synonyms": ["至", "到"], "antonyms": ["去", "走"]},
    "去": {"synonyms": ["走", "往"], "antonyms": ["来", "回"]},
    "走": {"synonyms": ["行", "步"], "antonyms": ["停", "留"]},
    "跑": {"synonyms": ["奔", "逃"], "antonyms": ["走", "停"]},
    "停": {"synonyms": ["止", "驻"], "antonyms": ["走", "行"]},
    "行": {"synonyms": ["走", "步"], "antonyms": ["止", "停"]},
    "坐": {"synonyms": [], "antonyms": ["站"]},
    "站": {"synonyms": ["立"], "antonyms": ["坐"]},
    "立": {"synonyms": ["站"], "antonyms": ["坐"]},
    "开": {"synonyms": ["启", "启"], "antonyms": ["关", "闭"]},
    "关": {"synonyms": ["闭", "合"], "antonyms": ["开", "启"]},
    "闭": {"synonyms": ["关", "合"], "antonyms": ["开", "启"]},
    "启": {"synonyms": ["开"], "antonyms": ["关", "闭"]},
    "进": {"synonyms": ["入", "内"], "antonyms": ["出", "退"]},
    "出": {"synonyms": ["外", "离"], "antonyms": ["进", "入"]},
    "入": {"synonyms": ["进", "内"], "antonyms": ["出", "退"]},
    "退": {"synonyms": ["撤", "缩"], "antonyms": ["进", "前"]},
    "前": {"synonyms": ["进", "先"], "antonyms": ["后", "退"]},
    "后": {"synonyms": ["迟", "晚"], "antonyms": ["前", "先"]},
    "上": {"synonyms": ["升", "登"], "antonyms": ["下", "降"]},
    "下": {"synonyms": ["降", "落"], "antonyms": ["上", "升"]},
    "拉": {"synonyms": ["扯", "拖"], "antonyms": ["推"]},
    "推": {"synonyms": [], "antonyms": ["拉", "扯"]},
    "买": {"synonyms": ["购"], "antonyms": ["卖"]},
    "卖": {"synonyms": ["售", "销"], "antonyms": ["买", "购"]},
    "购": {"synonyms": ["买"], "antonyms": ["卖", "售"]},
    "售": {"synonyms": ["卖", "销"], "antonyms": ["买", "购"]},
    "借": {"synonyms": ["贷"], "antonyms": ["还"]},
    "还": {"synonyms": ["退", "归"], "antonyms": ["借", "取"]},
    "给": {"synonyms": ["予", "赠"], "antonyms": ["取", "拿"]},
    "拿": {"synonyms": ["取", "抓"], "antonyms": ["给", "放"]},
    "放": {"synonyms": ["置", "搁"], "antonyms": ["拿", "取"]},
    "收": {"synonyms": ["纳", "接"], "antonyms": ["发", "放"]},
    "发": {"synonyms": ["送", "出"], "antonyms": ["收", "纳"]},
    "送": {"synonyms": ["赠", "给"], "antonyms": ["收", "接"]},
    "接": {"synonyms": ["收", "纳"], "antonyms": ["送", "发"]},
    "赠": {"synonyms": ["送", "给"], "antonyms": ["收", "接"]},
    "爱": {"synonyms": ["喜", "慕"], "antonyms": ["恨", "厌"]},
    "恨": {"synonyms": ["厌", "恶"], "antonyms": ["爱", "喜"]},
    "厌": {"synonyms": ["恨", "烦"], "antonyms": ["爱", "喜"]},
    "喜": {"synonyms": ["爱", "欢"], "antonyms": ["厌", "恨"]},
    "怕": {"synonyms": ["惧", "畏"], "antonyms": ["敢"]},
    "敢": {"synonyms": ["勇"], "antonyms": ["怕", "惧"]},
    "惧": {"synonyms": ["怕", "畏"], "antonyms": ["敢", "勇"]},
    "勇": {"synonyms": ["敢", "猛"], "antonyms": ["怯", "怕"]},
    "怯": {"synonyms": ["怕", "弱"], "antonyms": ["勇", "敢"]},
    "笑": {"synonyms": ["乐"], "antonyms": ["哭"]},
    "哭": {"synonyms": ["泣", "号"], "antonyms": ["笑", "乐"]},
    "泣": {"synonyms": ["哭"], "antonyms": ["笑"]},
    "活": {"synonyms": ["生", "存"], "antonyms": ["死"]},
    "死": {"synonyms": ["亡", "灭"], "antonyms": ["活", "生"]},
    "生": {"synonyms": ["活", "产"], "antonyms": ["死", "灭"]},
    "灭": {"synonyms": ["亡", "熄"], "antonyms": ["生", "燃"]},
    "燃": {"synonyms": ["烧", "点"], "antonyms": ["灭", "熄"]},
    "熄": {"synonyms": ["灭"], "antonyms": ["燃", "烧"]},
    "烧": {"synonyms": ["燃", "焚"], "antonyms": ["灭", "熄"]},
    "建": {"synonyms": ["造", "筑"], "antonyms": ["拆", "毁"]},
    "拆": {"synonyms": ["毁", "破"], "antonyms": ["建", "造"]},
    "毁": {"synonyms": ["拆", "坏"], "antonyms": ["建", "修"]},
    "修": {"synonyms": ["补", "缮"], "antonyms": ["毁", "坏"]},
    "补": {"synonyms": ["修", "填"], "antonyms": ["拆", "破"]},
    "打": {"synonyms": ["击", "敲"], "antonyms": ["护", "保"]},
    "击": {"synonyms": ["打", "攻"], "antonyms": ["守", "防"]},
    "攻": {"synonyms": ["击", "打"], "antonyms": ["守", "防"]},
    "守": {"synonyms": ["防", "护"], "antonyms": ["攻", "击"]},
    "防": {"synonyms": ["守", "护"], "antonyms": ["攻", "击"]},
    "护": {"synonyms": ["保", "守"], "antonyms": ["攻", "害"]},
    "战": {"synonyms": ["斗", "争"], "antonyms": ["和", "降"]},
    "和": {"synonyms": ["平", "谐"], "antonyms": ["战", "争"]},
    "争": {"synonyms": ["斗", "抢"], "antonyms": ["让", "和"]},
    "让": {"synonyms": ["退", "予"], "antonyms": ["争", "抢"]},
    "抢": {"synonyms": ["夺", "争"], "antonyms": ["让", "予"]},
    "夺": {"synonyms": ["抢", "取"], "antonyms": ["让", "给"]},
    "胜": {"synonyms": ["赢", "克"], "antonyms": ["败", "输"]},
    "败": {"synonyms": ["输", "负"], "antonyms": ["胜", "赢"]},
    "输": {"synonyms": ["败", "负"], "antonyms": ["赢", "胜"]},
    "赢": {"synonyms": ["胜", "克"], "antonyms": ["输", "败"]},
    "负": {"synonyms": ["败", "输"], "antonyms": ["胜", "赢"]},
    "克": {"synonyms": ["胜", "赢"], "antonyms": ["败", "负"]},
    "成": {"synonyms": ["就", "功"], "antonyms": ["败", "废"]},
    "败": {"synonyms": ["输", "负"], "antonyms": ["成", "胜"]},
    "功": {"synonyms": ["成", "就"], "antonyms": ["过", "败"]},
    "过": {"synonyms": ["错", "失"], "antonyms": ["功", "对"]},
    "对": {"synonyms": ["正", "是"], "antonyms": ["错", "非"]},
    "错": {"synonyms": ["误", "非"], "antonyms": ["对", "是"]},
    "非": {"synonyms": ["错", "否"], "antonyms": ["是", "对"]},
    "是": {"synonyms": ["对", "正"], "antonyms": ["非", "否"]},
    "否": {"synonyms": ["非"], "antonyms": ["是"]},
    "有": {"synonyms": ["具", "持"], "antonyms": ["无", "没"]},
    "无": {"synonyms": ["没", "空"], "antonyms": ["有", "具"]},
    "没": {"synonyms": ["无"], "antonyms": ["有"]},
    "具": {"synonyms": ["有", "备"], "antonyms": ["无", "缺"]},
    "持": {"synonyms": ["有", "保"], "antonyms": ["失", "弃"]},
    "弃": {"synonyms": ["丢", "舍"], "antonyms": ["持", "保"]},
    "舍": {"synonyms": ["弃", "丢"], "antonyms": ["取", "得"]},
    "变": {"synonyms": ["改", "化"], "antonyms": ["定", "恒"]},
    "定": {"synonyms": ["固", "稳"], "antonyms": ["变", "改"]},
    "改": {"synonyms": ["变", "换"], "antonyms": ["守", "保"]},
    "换": {"synonyms": ["替", "代"], "antonyms": ["留", "保"]},
    "代": {"synonyms": ["替", "换"], "antonyms": ["原", "旧"]},
    "替": {"synonyms": ["代", "换"], "antonyms": ["留", "保"]},
    "化": {"synonyms": ["变", "转"], "antonyms": ["定", "固"]},
    "转": {"synonyms": ["变", "旋"], "antonyms": ["停", "定"]},

    # === 名词 - 自然 ===
    "天": {"synonyms": ["空", "苍"], "antonyms": ["地"]},
    "地": {"synonyms": ["土", "壤"], "antonyms": ["天"]},
    "日": {"synonyms": ["阳", "昼"], "antonyms": ["月", "夜"]},
    "月": {"synonyms": ["阴"], "antonyms": ["日", "阳"]},
    "夜": {"synonyms": ["晚", "暮"], "antonyms": ["昼", "日"]},
    "昼": {"synonyms": ["日", "白"], "antonyms": ["夜", "晚"]},
    "昼": {"synonyms": ["日"], "antonyms": ["夜"]},
    "春": {"synonyms": [], "antonyms": ["秋"]},
    "夏": {"synonyms": [], "antonyms": ["冬"]},
    "秋": {"synonyms": [], "antonyms": ["春"]},
    "冬": {"synonyms": [], "antonyms": ["夏"]},
    "山": {"synonyms": ["岭", "峰"], "antonyms": ["谷", "水"]},
    "水": {"synonyms": ["液", "流"], "antonyms": ["火", "山"]},
    "火": {"synonyms": ["焰", "燃"], "antonyms": ["水", "冰"]},
    "冰": {"synonyms": ["冻", "霜"], "antonyms": ["火", "热"]},
    "风": {"synonyms": [], "antonyms": ["静"]},
    "雨": {"synonyms": [], "antonyms": ["晴"]},
    "晴": {"synonyms": [], "antonyms": ["雨", "阴"]},
    "阴": {"synonyms": ["暗", "沉"], "antonyms": ["晴", "阳"]},
    "阳": {"synonyms": ["光", "明"], "antonyms": ["阴", "暗"]},
    "光": {"synonyms": ["明", "亮"], "antonyms": ["暗", "黑"]},
    "海": {"synonyms": ["洋"], "antonyms": ["陆"]},
    "陆": {"synonyms": ["地", "岸"], "antonyms": ["海", "洋"]},
    "河": {"synonyms": ["江", "溪"], "antonyms": []},
    "树": {"synonyms": ["木", "林"], "antonyms": []},
    "花": {"synonyms": ["朵", "卉"], "antonyms": []},
    "草": {"synonyms": ["卉", "苗"], "antonyms": []},

    # === 名词 - 方位 ===
    "东": {"synonyms": [], "antonyms": ["西"]},
    "西": {"synonyms": [], "antonyms": ["东"]},
    "南": {"synonyms": [], "antonyms": ["北"]},
    "北": {"synonyms": [], "antonyms": ["南"]},
    "左": {"synonyms": [], "antonyms": ["右"]},
    "右": {"synonyms": [], "antonyms": ["左"]},
    "内": {"synonyms": ["里", "中"], "antonyms": ["外", "表"]},
    "外": {"synonyms": ["表"], "antonyms": ["内", "里"]},
    "里": {"synonyms": ["内", "中"], "antonyms": ["外", "表"]},
    "中": {"synonyms": ["内", "里"], "antonyms": ["外", "旁"]},
    "头": {"synonyms": ["首", "顶"], "antonyms": ["尾", "脚"]},
    "尾": {"synonyms": ["末", "后"], "antonyms": ["头", "首"]},
    "首": {"synonyms": ["头", "顶"], "antonyms": ["尾", "末"]},
    "末": {"synonyms": ["尾", "终"], "antonyms": ["初", "始"]},
    "始": {"synonyms": ["初", "起"], "antonyms": ["终", "末"]},
    "终": {"synonyms": ["末", "结"], "antonyms": ["始", "初"]},
    "初": {"synonyms": ["始", "起"], "antonyms": ["终", "末"]},
    "顶": {"synonyms": ["头", "峰"], "antonyms": ["底", "脚"]},
    "底": {"synonyms": ["下", "根"], "antonyms": ["顶", "头"]},

    # === 词语（二字词）===
    "快乐": {"synonyms": ["高兴", "欢乐", "愉快"], "antonyms": ["悲伤", "痛苦"]},
    "悲伤": {"synonyms": ["伤心", "难过", "哀伤"], "antonyms": ["快乐", "高兴"]},
    "高兴": {"synonyms": ["快乐", "愉快", "开心"], "antonyms": ["难过", "伤心"]},
    "难过": {"synonyms": ["伤心", "悲伤", "难受"], "antonyms": ["高兴", "快乐"]},
    "开心": {"synonyms": ["快乐", "高兴", "愉快"], "antonyms": ["难过", "伤心"]},
    "伤心": {"synonyms": ["难过", "悲伤"], "antonyms": ["开心", "高兴"]},
    "美丽": {"synonyms": ["漂亮", "好看", "秀美"], "antonyms": ["丑陋", "难看"]},
    "丑陋": {"synonyms": ["难看"], "antonyms": ["美丽", "漂亮"]},
    "漂亮": {"synonyms": ["美丽", "好看"], "antonyms": ["丑陋", "难看"]},
    "聪明": {"synonyms": ["智慧", "灵巧", "机灵"], "antonyms": ["愚笨", "愚蠢"]},
    "愚蠢": {"synonyms": ["愚笨", "笨拙"], "antonyms": ["聪明", "智慧"]},
    "勇敢": {"synonyms": ["英勇", "大胆"], "antonyms": ["胆小", "怯懦"]},
    "胆小": {"synonyms": ["怯懦", "畏缩"], "antonyms": ["勇敢", "英勇"]},
    "善良": {"synonyms": ["仁慈", "和善"], "antonyms": ["凶恶", "残忍"]},
    "残忍": {"synonyms": ["凶恶", "狠毒"], "antonyms": ["善良", "仁慈"]},
    "勤劳": {"synonyms": ["勤快", "勤奋"], "antonyms": ["懒惰", "懒散"]},
    "懒惰": {"synonyms": ["懒散", "懈怠"], "antonyms": ["勤劳", "勤奋"]},
    "勤奋": {"synonyms": ["勤劳", "努力"], "antonyms": ["懒惰", "懒散"]},
    "努力": {"synonyms": ["勤奋", "用功"], "antonyms": ["懈怠", "懒惰"]},
    "幸福": {"synonyms": ["美满", "幸运"], "antonyms": ["不幸", "痛苦"]},
    "不幸": {"synonyms": ["倒霉", "苦命"], "antonyms": ["幸福", "幸运"]},
    "安全": {"synonyms": ["平安", "稳妥"], "antonyms": ["危险", "凶险"]},
    "危险": {"synonyms": ["凶险", "危机"], "antonyms": ["安全", "平安"]},
    "简单": {"synonyms": ["容易", "简便"], "antonyms": ["复杂", "困难"]},
    "复杂": {"synonyms": ["繁杂", "繁琐"], "antonyms": ["简单", "容易"]},
    "容易": {"synonyms": ["简单", "轻松"], "antonyms": ["困难", "艰难"]},
    "困难": {"synonyms": ["艰难", "艰苦"], "antonyms": ["容易", "简单"]},
    "艰难": {"synonyms": ["困难", "艰苦"], "antonyms": ["容易", "轻松"]},
    "轻松": {"synonyms": ["容易", "轻快"], "antonyms": ["沉重", "艰难"]},
    "沉重": {"synonyms": ["繁重", "笨重"], "antonyms": ["轻松", "轻快"]},
    "温暖": {"synonyms": ["暖和", "温热"], "antonyms": ["寒冷", "冰冷"]},
    "寒冷": {"synonyms": ["冰冷", "严寒"], "antonyms": ["温暖", "暖和"]},
    "热闹": {"synonyms": ["喧闹", "繁华"], "antonyms": ["冷清", "安静"]},
    "冷清": {"synonyms": ["安静", "寂寞"], "antonyms": ["热闹", "喧闹"]},
    "安静": {"synonyms": ["宁静", "平静"], "antonyms": ["吵闹", "喧哗"]},
    "吵闹": {"synonyms": ["喧哗", "嘈杂"], "antonyms": ["安静", "宁静"]},
    "干净": {"synonyms": ["清洁", "整洁"], "antonyms": ["肮脏", "污浊"]},
    "肮脏": {"synonyms": ["污浊"], "antonyms": ["干净", "清洁"]},
    "整齐": {"synonyms": ["整洁", "井然"], "antonyms": ["凌乱", "杂乱"]},
    "凌乱": {"synonyms": ["杂乱", "紊乱"], "antonyms": ["整齐", "整洁"]},
    "丰富": {"synonyms": ["丰盛", "充沛"], "antonyms": ["贫乏", "单调"]},
    "贫乏": {"synonyms": ["单调", "匮乏"], "antonyms": ["丰富", "丰盛"]},
    "强大": {"synonyms": ["强盛", "雄厚"], "antonyms": ["弱小", "虚弱"]},
    "弱小": {"synonyms": ["虚弱", "微小"], "antonyms": ["强大", "强盛"]},
    "成功": {"synonyms": ["胜利", "成就"], "antonyms": ["失败", "挫折"]},
    "失败": {"synonyms": ["挫折", "落败"], "antonyms": ["成功", "胜利"]},
    "胜利": {"synonyms": ["成功", "凯旋"], "antonyms": ["失败", "败北"]},
    "喜欢": {"synonyms": ["喜爱", "爱好"], "antonyms": ["讨厌", "厌恶"]},
    "讨厌": {"synonyms": ["厌恶", "反感"], "antonyms": ["喜欢", "喜爱"]},
    "喜爱": {"synonyms": ["喜欢", "热爱"], "antonyms": ["讨厌", "厌恶"]},
    "厌恶": {"synonyms": ["讨厌", "反感"], "antonyms": ["喜爱", "喜欢"]},
    "相信": {"synonyms": ["信任", "信赖"], "antonyms": ["怀疑", "猜疑"]},
    "怀疑": {"synonyms": ["猜疑", "质疑"], "antonyms": ["相信", "信任"]},
    "信任": {"synonyms": ["相信", "信赖"], "antonyms": ["猜疑", "怀疑"]},
    "谦虚": {"synonyms": ["谦逊", "谦和"], "antonyms": ["骄傲", "傲慢"]},
    "骄傲": {"synonyms": ["傲慢", "自满"], "antonyms": ["谦虚", "谦逊"]},
    "诚实": {"synonyms": ["真诚", "老实"], "antonyms": ["虚伪", "欺骗"]},
    "虚伪": {"synonyms": ["虚假", "做作"], "antonyms": ["诚实", "真诚"]},
    "大方": {"synonyms": ["慷慨", "爽快"], "antonyms": ["小气", "吝啬"]},
    "小气": {"synonyms": ["吝啬", "抠门"], "antonyms": ["大方", "慷慨"]},
    "慷慨": {"synonyms": ["大方", "豪爽"], "antonyms": ["吝啬", "小气"]},
    "吝啬": {"synonyms": ["小气", "抠门"], "antonyms": ["大方", "慷慨"]},
    "积极": {"synonyms": ["主动", "进取"], "antonyms": ["消极", "被动"]},
    "消极": {"synonyms": ["被动", "颓废"], "antonyms": ["积极", "主动"]},
    "主动": {"synonyms": ["积极", "自发"], "antonyms": ["被动", "消极"]},
    "被动": {"synonyms": ["消极"], "antonyms": ["主动", "积极"]},
    "团结": {"synonyms": ["联合", "合作"], "antonyms": ["分裂", "分散"]},
    "分裂": {"synonyms": ["分散", "割裂"], "antonyms": ["团结", "联合"]},
    "合作": {"synonyms": ["协作", "配合"], "antonyms": ["对抗", "竞争"]},
    "竞争": {"synonyms": ["角逐", "争抢"], "antonyms": ["合作", "协作"]},
    "进步": {"synonyms": ["前进", "提高"], "antonyms": ["退步", "落后"]},
    "退步": {"synonyms": ["落后", "倒退"], "antonyms": ["进步", "前进"]},
    "前进": {"synonyms": ["进步", "迈进"], "antonyms": ["后退", "倒退"]},
    "后退": {"synonyms": ["倒退", "退缩"], "antonyms": ["前进", "进步"]},
    "增加": {"synonyms": ["增多", "增长"], "antonyms": ["减少", "降低"]},
    "减少": {"synonyms": ["降低", "缩减"], "antonyms": ["增加", "增多"]},
    "增长": {"synonyms": ["增加", "提升"], "antonyms": ["下降", "减少"]},
    "下降": {"synonyms": ["降低", "减少"], "antonyms": ["增长", "上升"]},
    "上升": {"synonyms": ["增长", "提高"], "antonyms": ["下降", "降低"]},
    "提高": {"synonyms": ["提升", "升高"], "antonyms": ["降低", "下降"]},
    "降低": {"synonyms": ["下降", "减少"], "antonyms": ["提高", "上升"]},
    "建造": {"synonyms": ["建设", "修建"], "antonyms": ["拆除", "破坏"]},
    "拆除": {"synonyms": ["拆毁", "拆掉"], "antonyms": ["建造", "建设"]},
    "保护": {"synonyms": ["维护", "守护"], "antonyms": ["破坏", "伤害"]},
    "破坏": {"synonyms": ["损坏", "毁坏"], "antonyms": ["保护", "维护"]},
    "帮助": {"synonyms": ["协助", "援助"], "antonyms": ["阻碍", "妨碍"]},
    "阻碍": {"synonyms": ["妨碍", "阻挡"], "antonyms": ["帮助", "促进"]},
    "促进": {"synonyms": ["推动", "推进"], "antonyms": ["阻碍", "妨碍"]},
    "吸收": {"synonyms": ["吸纳", "吸取"], "antonyms": ["释放", "排出"]},
    "释放": {"synonyms": ["放出", "排放"], "antonyms": ["吸收", "吸纳"]},
    "聚集": {"synonyms": ["集合", "汇聚"], "antonyms": ["分散", "散开"]},
    "分散": {"synonyms": ["散开", "分散"], "antonyms": ["聚集", "集合"]},
    "支持": {"synonyms": ["拥护", "赞成"], "antonyms": ["反对", "抵制"]},
    "反对": {"synonyms": ["抵制", "抗拒"], "antonyms": ["支持", "赞成"]},
    "赞成": {"synonyms": ["同意", "赞同"], "antonyms": ["反对", "否定"]},
    "反对": {"synonyms": ["反对", "抵制"], "antonyms": ["赞成", "支持"]},
    "同意": {"synonyms": ["赞成", "认可"], "antonyms": ["反对", "拒绝"]},
    "拒绝": {"synonyms": ["回绝", "谢绝"], "antonyms": ["同意", "接受"]},
    "接受": {"synonyms": ["接纳", "接收"], "antonyms": ["拒绝", "推辞"]},
    "表扬": {"synonyms": ["夸奖", "赞美"], "antonyms": ["批评", "责备"]},
    "批评": {"synonyms": ["指责", "责备"], "antonyms": ["表扬", "赞美"]},
    "赞美": {"synonyms": ["表扬", "夸奖"], "antonyms": ["批评", "贬低"]},
    "夸奖": {"synonyms": ["表扬", "称赞"], "antonyms": ["批评", "责备"]},
    "奖励": {"synonyms": ["奖赏", "嘉奖"], "antonyms": ["惩罚", "处罚"]},
    "惩罚": {"synonyms": ["处罚", "惩戒"], "antonyms": ["奖励", "奖赏"]},
    "鼓励": {"synonyms": ["激励", "勉励"], "antonyms": ["打击", "泄气"]},
    "打击": {"synonyms": ["压制", "挫伤"], "antonyms": ["鼓励", "激励"]},
    "开始": {"synonyms": ["起始", "开端"], "antonyms": ["结束", "完毕"]},
    "结束": {"synonyms": ["完毕", "终了"], "antonyms": ["开始", "起始"]},
    "出现": {"synonyms": ["显现", "浮现"], "antonyms": ["消失", "隐没"]},
    "消失": {"synonyms": ["消逝", "隐没"], "antonyms": ["出现", "显现"]},
    "存在": {"synonyms": ["存有", "实存"], "antonyms": ["消亡", "消失"]},
    "消亡": {"synonyms": ["灭亡", "消失"], "antonyms": ["存在", "生存"]},
    "生存": {"synonyms": ["存活", "生活"], "antonyms": ["死亡", "灭亡"]},
    "死亡": {"synonyms": ["逝世", "去世"], "antonyms": ["生存", "活着"]},
    "光明": {"synonyms": ["明亮", "光辉"], "antonyms": ["黑暗", "阴暗"]},
    "黑暗": {"synonyms": ["阴暗", "昏暗"], "antonyms": ["光明", "明亮"]},
    "公开": {"synonyms": ["公然", "透明"], "antonyms": ["秘密", "隐蔽"]},
    "秘密": {"synonyms": ["隐蔽", "暗藏"], "antonyms": ["公开", "透明"]},
    "真实": {"synonyms": ["确实", "真切"], "antonyms": ["虚假", "虚构"]},
    "虚假": {"synonyms": ["虚构", "伪造"], "antonyms": ["真实", "确实"]},
    "完整": {"synonyms": ["完好", "齐全"], "antonyms": ["残缺", "破损"]},
    "残缺": {"synonyms": ["破损", "不完整"], "antonyms": ["完整", "完好"]},
    "清楚": {"synonyms": ["清晰", "明白"], "antonyms": ["模糊", "含糊"]},
    "模糊": {"synonyms": ["含糊", "朦胧"], "antonyms": ["清楚", "清晰"]},
    "清晰": {"synonyms": ["清楚", "明朗"], "antonyms": ["模糊", "朦胧"]},
    "坚强": {"synonyms": ["刚强", "坚韧"], "antonyms": ["脆弱", "软弱"]},
    "脆弱": {"synonyms": ["软弱", "柔弱"], "antonyms": ["坚强", "刚强"]},
    "热闹": {"synonyms": ["喧闹", "繁华"], "antonyms": ["冷清", "安静"]},
    "繁荣": {"synonyms": ["兴旺", "昌盛"], "antonyms": ["萧条", "衰败"]},
    "萧条": {"synonyms": ["衰败", "凋敝"], "antonyms": ["繁荣", "兴旺"]},
    "兴盛": {"synonyms": ["兴旺", "昌盛"], "antonyms": ["衰落", "衰退"]},
    "衰落": {"synonyms": ["衰退", "没落"], "antonyms": ["兴盛", "兴旺"]},
    "和平": {"synonyms": ["安宁", "太平"], "antonyms": ["战争", "动乱"]},
    "战争": {"synonyms": ["战乱", "冲突"], "antonyms": ["和平", "安宁"]},
    "自由": {"synonyms": ["解放", "自主"], "antonyms": ["束缚", "限制"]},
    "束缚": {"synonyms": ["限制", "约束"], "antonyms": ["自由", "解放"]},
    "团结": {"synonyms": ["联合", "凝聚"], "antonyms": ["分裂", "涣散"]},
    "分裂": {"synonyms": ["分化", "割裂"], "antonyms": ["团结", "联合"]},
    "节约": {"synonyms": ["节省", "节俭"], "antonyms": ["浪费", "奢侈"]},
    "浪费": {"synonyms": ["挥霍", "奢侈"], "antonyms": ["节约", "节省"]},
    "奢侈": {"synonyms": ["奢华", "铺张"], "antonyms": ["节俭", "朴素"]},
    "朴素": {"synonyms": ["简朴", "朴实"], "antonyms": ["奢侈", "华丽"]},
    "华丽": {"synonyms": ["奢华", "绚烂"], "antonyms": ["朴素", "简朴"]},
    "崭新": {"synonyms": ["全新", "簇新"], "antonyms": ["破旧", "陈旧"]},
    "破旧": {"synonyms": ["陈旧", "老旧"], "antonyms": ["崭新", "全新"]},
    "紧密": {"synonyms": ["密切", "亲密"], "antonyms": ["疏远", "松散"]},
    "疏远": {"synonyms": ["远离", "冷淡"], "antonyms": ["亲密", "密切"]},
    "亲密": {"synonyms": ["亲近", "密切"], "antonyms": ["疏远", "冷淡"]},
    "冷淡": {"synonyms": ["冷漠", "淡漠"], "antonyms": ["热情", "热心"]},
    "热情": {"synonyms": ["热心", "热烈"], "antonyms": ["冷淡", "冷漠"]},
    "冷漠": {"synonyms": ["冷淡", "漠然"], "antonyms": ["热情", "温暖"]},
    "温暖": {"synonyms": ["暖和", "温热"], "antonyms": ["寒冷", "冷漠"]},
    "严格": {"synonyms": ["严厉", "严谨"], "antonyms": ["宽松", "宽容"]},
    "宽松": {"synonyms": ["宽容", "宽大"], "antonyms": ["严格", "严厉"]},
    "宽容": {"synonyms": ["宽大", "包容"], "antonyms": ["苛刻", "严厉"]},
    "苛刻": {"synonyms": ["严厉", "刻薄"], "antonyms": ["宽容", "宽厚"]},
    "精确": {"synonyms": ["精准", "准确"], "antonyms": ["粗略", "模糊"]},
    "准确": {"synonyms": ["正确", "精确"], "antonyms": ["错误", "偏差"]},
    "错误": {"synonyms": ["过失", "谬误"], "antonyms": ["正确", "准确"]},
    "正确": {"synonyms": ["对", "无误"], "antonyms": ["错误", "不对"]},
    "永久": {"synonyms": ["永恒", "长久"], "antonyms": ["暂时", "短暂"]},
    "暂时": {"synonyms": ["临时", "短暂"], "antonyms": ["永久", "长久"]},
    "永恒": {"synonyms": ["永久", "不朽"], "antonyms": ["短暂", "瞬间"]},
    "短暂": {"synonyms": ["瞬间", "片刻"], "antonyms": ["长久", "永恒"]},
    "长久": {"synonyms": ["持久", "长远"], "antonyms": ["短暂", "片刻"]},
    "迅速": {"synonyms": ["快速", "敏捷"], "antonyms": ["缓慢", "迟钝"]},
    "缓慢": {"synonyms": ["迟缓", "慢慢"], "antonyms": ["迅速", "快速"]},
    "迟钝": {"synonyms": ["笨拙", "呆滞"], "antonyms": ["敏捷", "灵敏"]},
    "敏捷": {"synonyms": ["灵敏", "灵活"], "antonyms": ["迟钝", "笨拙"]},
    "灵活": {"synonyms": ["敏捷", "灵巧"], "antonyms": ["死板", "僵硬"]},
    "僵硬": {"synonyms": ["死板", "呆板"], "antonyms": ["灵活", "柔软"]},
    "坚定": {"synonyms": ["坚决", "稳固"], "antonyms": ["动摇", "犹豫"]},
    "动摇": {"synonyms": ["犹豫", "摇摆"], "antonyms": ["坚定", "坚决"]},
    "犹豫": {"synonyms": ["迟疑", "踌躇"], "antonyms": ["果断", "坚定"]},
    "果断": {"synonyms": ["决断", "坚决"], "antonyms": ["犹豫", "迟疑"]},
    "明显": {"synonyms": ["显著", "显然"], "antonyms": ["隐蔽", "隐约"]},
    "隐蔽": {"synonyms": ["隐藏", "隐秘"], "antonyms": ["明显", "显露"]},
    "显赫": {"synonyms": ["显耀", "著名"], "antonyms": ["卑微", "无名"]},
    "卑微": {"synonyms": ["低微", "渺小"], "antonyms": ["显赫", "崇高"]},
    "崇高": {"synonyms": ["高尚", "伟大"], "antonyms": ["卑劣", "低俗"]},
    "卑劣": {"synonyms": ["恶劣", "下流"], "antonyms": ["崇高", "高尚"]},
    "高尚": {"synonyms": ["崇高", "高贵"], "antonyms": ["卑鄙", "低俗"]},
    "卑鄙": {"synonyms": ["卑劣", "下作"], "antonyms": ["高尚", "正派"]},
    "正派": {"synonyms": ["正直", "正经"], "antonyms": ["卑鄙", "邪门"]},
    "正直": {"synonyms": ["正派", "刚正"], "antonyms": ["奸诈", "歪斜"]},
    "奸诈": {"synonyms": ["狡猾", "阴险"], "antonyms": ["正直", "老实"]},
    "狡猾": {"synonyms": ["奸诈", "诡诈"], "antonyms": ["老实", "厚道"]},
    "老实": {"synonyms": ["厚道", "诚实"], "antonyms": ["狡猾", "奸诈"]},
    "厚道": {"synonyms": ["老实", "宽厚"], "antonyms": ["刻薄", "尖酸"]},
    "刻薄": {"synonyms": ["尖酸", "苛刻"], "antonyms": ["厚道", "宽厚"]},
    "宽厚": {"synonyms": ["宽大", "仁厚"], "antonyms": ["刻薄", "严苛"]},

    # === 更多二字词 ===
    "表扬": {"synonyms": ["表彰", "称赞"], "antonyms": ["批评", "谴责"]},
    "谴责": {"synonyms": ["声讨", "斥责"], "antonyms": ["表扬", "赞扬"]},
    "赞扬": {"synonyms": ["称颂", "颂扬"], "antonyms": ["谴责", "批评"]},
    "奖励": {"synonyms": ["嘉奖", "赏赐"], "antonyms": ["惩罚", "处罚"]},
    "处罚": {"synonyms": ["惩罚", "惩戒"], "antonyms": ["奖励", "嘉奖"]},
    "丰富": {"synonyms": ["丰盛", "充沛"], "antonyms": ["贫乏", "匮乏"]},
    "匮乏": {"synonyms": ["贫乏", "短缺"], "antonyms": ["丰富", "充裕"]},
    "充裕": {"synonyms": ["充足", "宽裕"], "antonyms": ["匮乏", "紧缺"]},
    "紧缺": {"synonyms": ["缺乏", "短缺"], "antonyms": ["充裕", "充足"]},
    "充足": {"synonyms": ["充裕", "充分"], "antonyms": ["不足", "缺乏"]},
    "缺乏": {"synonyms": ["不足", "缺少"], "antonyms": ["充足", "充裕"]},
    "茂盛": {"synonyms": ["繁茂", "旺盛"], "antonyms": ["枯萎", "凋零"]},
    "枯萎": {"synonyms": ["凋零", "干枯"], "antonyms": ["茂盛", "繁茂"]},
    "绽放": {"synonyms": ["盛开", "开放"], "antonyms": ["凋谢", "枯萎"]},
    "凋谢": {"synonyms": ["枯萎", "凋落"], "antonyms": ["绽放", "盛开"]},
    "明亮": {"synonyms": ["光亮", "明朗"], "antonyms": ["昏暗", "阴暗"]},
    "昏暗": {"synonyms": ["阴暗", "幽暗"], "antonyms": ["明亮", "光亮"]},
    "宽敞": {"synonyms": ["宽大", "开阔"], "antonyms": ["狭窄", "狭小"]},
    "狭窄": {"synonyms": ["狭小", "窄小"], "antonyms": ["宽敞", "宽阔"]},
    "宽阔": {"synonyms": ["宽广", "辽阔"], "antonyms": ["狭窄", "狭小"]},
    "辽阔": {"synonyms": ["广阔", "宽广"], "antonyms": ["狭小", "狭窄"]},
    "坚固": {"synonyms": ["牢固", "结实"], "antonyms": ["脆弱", "松散"]},
    "脆弱": {"synonyms": ["薄弱", "易碎"], "antonyms": ["坚固", "牢固"]},
    "牢固": {"synonyms": ["坚固", "稳固"], "antonyms": ["松动", "松散"]},
    "松动": {"synonyms": ["松散", "不稳"], "antonyms": ["牢固", "稳固"]},
    "稳固": {"synonyms": ["稳定", "坚固"], "antonyms": ["动摇", "不稳"]},
    "动摇": {"synonyms": ["不稳", "摇摆"], "antonyms": ["稳固", "坚定"]},
    "稳定": {"synonyms": ["稳固", "安定"], "antonyms": ["动荡", "波动"]},
    "动荡": {"synonyms": ["波动", "不安"], "antonyms": ["稳定", "安定"]},
    "安定": {"synonyms": ["稳定", "安宁"], "antonyms": ["动荡", "混乱"]},
    "混乱": {"synonyms": ["杂乱", "无序"], "antonyms": ["安定", "秩序"]},
    "秩序": {"synonyms": ["条理", "规范"], "antonyms": ["混乱", "无序"]},
    "无序": {"synonyms": ["混乱", "杂乱"], "antonyms": ["有序", "秩序"]},
    "有序": {"synonyms": ["秩序", "条理"], "antonyms": ["无序", "混乱"]},
    "统一": {"synonyms": ["一致", "整合"], "antonyms": ["分裂", "分散"]},
    "一致": {"synonyms": ["统一", "相同"], "antonyms": ["分歧", "矛盾"]},
    "分歧": {"synonyms": ["矛盾", "差异"], "antonyms": ["一致", "统一"]},
    "矛盾": {"synonyms": ["冲突", "对立"], "antonyms": ["和谐", "统一"]},
    "和谐": {"synonyms": ["融洽", "协调"], "antonyms": ["矛盾", "冲突"]},
    "冲突": {"synonyms": ["矛盾", "对抗"], "antonyms": ["和谐", "协调"]},
    "协调": {"synonyms": ["调和", "配合"], "antonyms": ["冲突", "矛盾"]},
    "融洽": {"synonyms": ["和谐", "和睦"], "antonyms": ["紧张", "对立"]},
    "和睦": {"synonyms": ["融洽", "和气"], "antonyms": ["不和", "争吵"]},
    "不和": {"synonyms": ["争吵", "反目"], "antonyms": ["和睦", "融洽"]},
    "快乐": {"synonyms": ["欢乐", "愉快"], "antonyms": ["痛苦", "忧愁"]},
    "痛苦": {"synonyms": ["苦楚", "煎熬"], "antonyms": ["快乐", "幸福"]},
    "忧愁": {"synonyms": ["忧虑", "愁苦"], "antonyms": ["快乐", "欢乐"]},
    "忧虑": {"synonyms": ["担忧", "焦虑"], "antonyms": ["安心", "放心"]},
    "安心": {"synonyms": ["放心", "踏实"], "antonyms": ["忧虑", "担心"]},
    "放心": {"synonyms": ["安心", "宽心"], "antonyms": ["担心", "忧虑"]},
    "担心": {"synonyms": ["忧虑", "担忧"], "antonyms": ["放心", "安心"]},
    "恐惧": {"synonyms": ["害怕", "畏惧"], "antonyms": ["勇敢", "无畏"]},
    "无畏": {"synonyms": ["勇敢", "大胆"], "antonyms": ["恐惧", "害怕"]},
    "惊慌": {"synonyms": ["慌张", "惊恐"], "antonyms": ["镇定", "冷静"]},
    "镇定": {"synonyms": ["冷静", "沉着"], "antonyms": ["惊慌", "慌张"]},
    "冷静": {"synonyms": ["镇定", "沉着"], "antonyms": ["冲动", "激动"]},
    "冲动": {"synonyms": ["激动", "鲁莽"], "antonyms": ["冷静", "理智"]},
    "理智": {"synonyms": ["理性", "清醒"], "antonyms": ["冲动", "盲目"]},
    "盲目": {"synonyms": ["盲从", "无目"], "antonyms": ["理智", "明智"]},
    "明智": {"synonyms": ["聪明", "睿智"], "antonyms": ["愚蠢", "糊涂"]},
    "糊涂": {"synonyms": ["迷糊", "困惑"], "antonyms": ["清醒", "明白"]},
    "清醒": {"synonyms": ["明白", "理智"], "antonyms": ["糊涂", "迷糊"]},
    "明白": {"synonyms": ["清楚", "懂得"], "antonyms": ["糊涂", "困惑"]},
    "困惑": {"synonyms": ["迷惑", "不解"], "antonyms": ["明白", "清楚"]},
    "积极": {"synonyms": ["主动", "热情"], "antonyms": ["消极", "被动"]},
    "消极": {"synonyms": ["被动", "颓废"], "antonyms": ["积极", "主动"]},
    "颓废": {"synonyms": ["消沉", "萎靡"], "antonyms": ["振奋", "积极"]},
    "振奋": {"synonyms": ["鼓舞", "激昂"], "antonyms": ["颓废", "消沉"]},
    "消沉": {"synonyms": ["颓废", "低落"], "antonyms": ["振奋", "高涨"]},
    "高涨": {"synonyms": ["上升", "激昂"], "antonyms": ["消沉", "低落"]},
    "低落": {"synonyms": ["消沉", "低沉"], "antonyms": ["高涨", "昂扬"]},
    "昂扬": {"synonyms": ["高涨", "激昂"], "antonyms": ["低落", "消沉"]},
    "灿烂": {"synonyms": ["辉煌", "绚烂"], "antonyms": ["暗淡", "昏暗"]},
    "辉煌": {"synonyms": ["灿烂", "光辉"], "antonyms": ["黯淡", "暗淡"]},
    "暗淡": {"synonyms": ["昏暗", "黯淡"], "antonyms": ["灿烂", "辉煌"]},
    "绚烂": {"synonyms": ["灿烂", "绚丽"], "antonyms": ["暗淡", "平淡"]},
    "绚丽": {"synonyms": ["绚烂", "华丽"], "antonyms": ["朴素", "平淡"]},
    "平淡": {"synonyms": ["平凡", "普通"], "antonyms": ["精彩", "绚丽"]},
    "精彩": {"synonyms": ["出色", "出众"], "antonyms": ["平淡", "平庸"]},
    "平庸": {"synonyms": ["平凡", "普通"], "antonyms": ["出色", "杰出"]},
    "杰出": {"synonyms": ["卓越", "优秀"], "antonyms": ["平庸", "平凡"]},
    "卓越": {"synonyms": ["杰出", "优异"], "antonyms": ["平庸", "平凡"]},
    "优秀": {"synonyms": ["杰出", "出色"], "antonyms": ["低劣", "差劲"]},
    "低劣": {"synonyms": ["差劲", "粗劣"], "antonyms": ["优秀", "出色"]},
    "出色": {"synonyms": ["优秀", "杰出"], "antonyms": ["平庸", "差劲"]},
    "差劲": {"synonyms": ["低劣", "糟糕"], "antonyms": ["出色", "优秀"]},
    "糟糕": {"synonyms": ["差劲", "恶劣"], "antonyms": ["出色", "优秀"]},
    "恶劣": {"synonyms": ["糟糕", "很差"], "antonyms": ["优良", "出色"]},
    "优良": {"synonyms": ["优秀", "良好"], "antonyms": ["恶劣", "低劣"]},
    "良好": {"synonyms": ["优良", "不错"], "antonyms": ["恶劣", "糟糕"]},
    "不错": {"synonyms": ["良好", "可以"], "antonyms": ["糟糕", "不好"]},
    "美好": {"synonyms": ["美妙", "幸福"], "antonyms": ["糟糕", "丑恶"]},
    "丑恶": {"synonyms": ["丑陋", "邪恶"], "antonyms": ["美好", "善良"]},
    "邪恶": {"synonyms": ["恶劣", "罪恶"], "antonyms": ["正义", "善良"]},
    "正义": {"synonyms": ["公正", "公道"], "antonyms": ["邪恶", "不公"]},
    "不公": {"synonyms": ["偏袒", "不义"], "antonyms": ["正义", "公平"]},
    "公平": {"synonyms": ["公正", "公道"], "antonyms": ["不公", "偏袒"]},
    "偏袒": {"synonyms": ["偏心", "偏向"], "antonyms": ["公正", "公平"]},
    "公正": {"synonyms": ["公平", "公道"], "antonyms": ["偏袒", "不公"]},
    "严格": {"synonyms": ["严厉", "严苛"], "antonyms": ["宽松", "宽大"]},
    "严厉": {"synonyms": ["严格", "严肃"], "antonyms": ["温和", "宽松"]},
    "温和": {"synonyms": ["柔和", "和蔼"], "antonyms": ["严厉", "粗暴"]},
    "粗暴": {"synonyms": ["蛮横", "凶暴"], "antonyms": ["温和", "和蔼"]},
    "和蔼": {"synonyms": ["和善", "亲切"], "antonyms": ["凶狠", "严厉"]},
    "凶狠": {"synonyms": ["凶恶", "残暴"], "antonyms": ["和蔼", "善良"]},
    "残暴": {"synonyms": ["凶残", "残忍"], "antonyms": ["仁慈", "善良"]},
    "仁慈": {"synonyms": ["慈善", "慈悲"], "antonyms": ["残暴", "凶狠"]},
    "慈悲": {"synonyms": ["仁慈", "怜悯"], "antonyms": ["残忍", "无情"]},
    "无情": {"synonyms": ["冷酷", "绝情"], "antonyms": ["多情", "有情"]},
    "多情": {"synonyms": ["深情", "重情"], "antonyms": ["无情", "冷酷"]},
    "深情": {"synonyms": ["深情", "厚意"], "antonyms": ["薄情", "无情"]},
    "薄情": {"synonyms": ["无情", "寡义"], "antonyms": ["深情", "多情"]},
    "忠诚": {"synonyms": ["忠实", "忠心"], "antonyms": ["背叛", "叛逆"]},
    "背叛": {"synonyms": ["叛逆", "出卖"], "antonyms": ["忠诚", "忠实"]},
    "叛逆": {"synonyms": ["反叛", "叛变"], "antonyms": ["忠诚", "顺从"]},
    "顺从": {"synonyms": ["服从", "听从"], "antonyms": ["反抗", "叛逆"]},
    "反抗": {"synonyms": ["抵御", "抵抗"], "antonyms": ["顺从", "服从"]},
    "抵抗": {"synonyms": ["反抗", "抵御"], "antonyms": ["投降", "屈服"]},
    "投降": {"synonyms": ["屈服", "归顺"], "antonyms": ["抵抗", "反抗"]},
    "屈服": {"synonyms": ["投降", "妥协"], "antonyms": ["抗争", "反抗"]},
    "抗争": {"synonyms": ["反抗", "斗争"], "antonyms": ["屈服", "投降"]},
    "屈服": {"synonyms": ["妥协", "让步"], "antonyms": ["坚持", "抗争"]},
    "坚持": {"synonyms": ["坚守", "执着"], "antonyms": ["放弃", "退缩"]},
    "放弃": {"synonyms": ["抛弃", "舍弃"], "antonyms": ["坚持", "坚守"]},
    "坚守": {"synonyms": ["坚持", "守卫"], "antonyms": ["放弃", "撤退"]},
    "撤退": {"synonyms": ["退却", "撤走"], "antonyms": ["坚守", "进攻"]},
    "进攻": {"synonyms": ["攻击", "进击"], "antonyms": ["防守", "撤退"]},
    "防守": {"synonyms": ["防御", "守卫"], "antonyms": ["进攻", "攻击"]},
    "防御": {"synonyms": ["防守", "防范"], "antonyms": ["攻击", "进攻"]},
    "攻击": {"synonyms": ["进攻", "打击"], "antonyms": ["防御", "防守"]},
    "打击": {"synonyms": ["攻击", "冲击"], "antonyms": ["保护", "维护"]},
    "维护": {"synonyms": ["保护", "维持"], "antonyms": ["破坏", "损害"]},
    "损害": {"synonyms": ["伤害", "损坏"], "antonyms": ["维护", "保护"]},
    "保护": {"synonyms": ["维护", "保卫"], "antonyms": ["损害", "破坏"]},
    "破坏": {"synonyms": ["毁坏", "损坏"], "antonyms": ["保护", "建设"]},
    "建设": {"synonyms": ["建造", "创建"], "antonyms": ["破坏", "毁坏"]},
    "创建": {"synonyms": ["创立", "创办"], "antonyms": ["毁灭", "废除"]},
    "废除": {"synonyms": ["取消", "废止"], "antonyms": ["建立", "创建"]},
    "建立": {"synonyms": ["创建", "设立"], "antonyms": ["废除", "取消"]},
    "取消": {"synonyms": ["废除", "撤消"], "antonyms": ["建立", "设立"]},
    "设立": {"synonyms": ["建立", "设置"], "antonyms": ["取消", "撤销"]},
    "撤销": {"synonyms": ["取消", "撤除"], "antonyms": ["设立", "建立"]},
    "增光": {"synonyms": ["添彩", "争光"], "antonyms": ["抹黑", "丢脸"]},
    "抹黑": {"synonyms": ["丢脸", "败坏"], "antonyms": ["争光", "增光"]},
    "争光": {"synonyms": ["增光", "争气"], "antonyms": ["丢人", "抹黑"]},
    "丢人": {"synonyms": ["丢脸", "丢丑"], "antonyms": ["争光", "争气"]},
    "争气": {"synonyms": ["争光", "出息"], "antonyms": ["丢人", "泄气"]},
    "出息": {"synonyms": ["前途", "作为"], "antonyms": ["没落", "沦落"]},
    "没落": {"synonyms": ["衰落", "衰败"], "antonyms": ["兴起", "崛起"]},
    "兴起": {"synonyms": ["崛起", "兴盛"], "antonyms": ["没落", "衰落"]},
    "崛起": {"synonyms": ["兴起", "腾飞"], "antonyms": ["没落", "衰败"]},
    "腾飞": {"synonyms": ["飞腾", "飞跃"], "antonyms": ["衰落", "没落"]},
    "衰落": {"synonyms": ["衰败", "没落"], "antonyms": ["兴盛", "崛起"]},
    "兴盛": {"synonyms": ["繁荣", "昌盛"], "antonyms": ["衰落", "衰败"]},
    "昌盛": {"synonyms": ["兴盛", "繁荣"], "antonyms": ["衰落", "萧条"]},
    "繁荣": {"synonyms": ["昌盛", "兴旺"], "antonyms": ["萧条", "衰败"]},
    "兴旺": {"synonyms": ["繁荣", "兴盛"], "antonyms": ["萧条", "衰落"]},
    "萧条": {"synonyms": ["衰落", "凋敝"], "antonyms": ["繁荣", "兴旺"]},
    "凋敝": {"synonyms": ["萧条", "衰败"], "antonyms": ["繁荣", "兴旺"]},

    # === 更多单字 ===
    "甜": {"synonyms": ["甘", "蜜"], "antonyms": ["苦", "涩"]},
    "蜜": {"synonyms": ["甜"], "antonyms": ["苦"]},
    "甘": {"synonyms": ["甜"], "antonyms": ["苦"]},
    "涩": {"synonyms": ["酸"], "antonyms": ["甜", "甘"]},
    "辛": {"synonyms": ["辣"], "antonyms": ["甘", "甜"]},
    "淡": {"synonyms": ["素", "寡"], "antonyms": ["浓", "咸"]},
    "浓": {"synonyms": ["厚", "重"], "antonyms": ["淡", "稀"]},
    "稀": {"synonyms": ["薄", "淡"], "antonyms": ["浓", "稠"]},
    "稠": {"synonyms": ["浓", "厚"], "antonyms": ["稀", "薄"]},
    "清": {"synonyms": ["净", "澄"], "antonyms": ["浊", "浑"]},
    "浊": {"synonyms": ["浑", "混"], "antonyms": ["清", "净"]},
    "浑": {"synonyms": ["浊", "混"], "antonyms": ["清", "澄"]},
    "澄": {"synonyms": ["清", "明"], "antonyms": ["浑", "浊"]},
    "混": {"synonyms": ["浊", "杂"], "antonyms": ["清", "纯"]},
    "纯": {"synonyms": ["净", "真"], "antonyms": ["杂", "混"]},
    "杂": {"synonyms": ["混", "乱"], "antonyms": ["纯", "净"]},
    "繁": {"synonyms": ["多", "盛"], "antonyms": ["简", "寡"]},
    "简": {"synonyms": ["单", "略"], "antonyms": ["繁", "详"]},
    "详": {"synonyms": ["细", "备"], "antonyms": ["简", "略"]},
    "略": {"synonyms": ["简", "粗"], "antonyms": ["详", "细"]},
    "粗": {"synonyms": ["略", "大"], "antonyms": ["细", "精"]},
    "精": {"synonyms": ["细", "准"], "antonyms": ["粗", "略"]},
    "准": {"synonyms": ["精", "确"], "antonyms": ["偏", "差"]},
    "确": {"synonyms": ["准", "真"], "antonyms": ["假", "错"]},
    "偏": {"synonyms": ["歪", "侧"], "antonyms": ["正", "中"]},
    "中": {"synonyms": ["正", "里"], "antonyms": ["偏", "侧"]},
    "侧": {"synonyms": ["旁", "偏"], "antonyms": ["正", "中"]},
    "旁": {"synonyms": ["侧", "边"], "antonyms": ["中", "正"]},
    "边": {"synonyms": ["旁", "缘"], "antonyms": ["中", "心"]},
    "心": {"synonyms": ["中", "内"], "antonyms": ["边", "外"]},
    "内": {"synonyms": ["里", "中"], "antonyms": ["外", "表"]},
    "表": {"synonyms": ["外", "面"], "antonyms": ["里", "内"]},
    "面": {"synonyms": ["表", "脸"], "antonyms": ["底", "背"]},
    "底": {"synonyms": ["下", "根"], "antonyms": ["顶", "面"]},
    "背": {"synonyms": ["后", "反"], "antonyms": ["正", "面"]},
    "反": {"synonyms": ["背", "逆"], "antonyms": ["正", "顺"]},
    "顺": {"synonyms": ["畅", "利"], "antonyms": ["逆", "阻"]},
    "阻": {"synonyms": ["碍", "挡"], "antonyms": ["顺", "畅"]},
    "碍": {"synonyms": ["阻", "妨"], "antonyms": ["助", "帮"]},
    "助": {"synonyms": ["帮", "辅"], "antonyms": ["碍", "阻"]},
    "帮": {"synonyms": ["助", "援"], "antonyms": ["害", "阻"]},
    "援": {"synonyms": ["助", "救"], "antonyms": ["攻", "害"]},
    "救": {"synonyms": ["援", "护"], "antonyms": ["害", "伤"]},
    "害": {"synonyms": ["伤", "损"], "antonyms": ["救", "护"]},
    "伤": {"synonyms": ["害", "损"], "antonyms": ["治", "愈"]},
    "治": {"synonyms": ["理", "管"], "antonyms": ["乱", "害"]},
    "愈": {"synonyms": ["康", "好"], "antonyms": ["病", "伤"]},
    "病": {"synonyms": ["疾", "患"], "antonyms": ["康", "健"]},
    "疾": {"synonyms": ["病", "速"], "antonyms": ["康"]},
    "康": {"synonyms": ["健", "安"], "antonyms": ["病", "疾"]},
    "患": {"synonyms": ["病", "忧"], "antonyms": ["安", "康"]},
    "忧": {"synonyms": ["愁", "患"], "antonyms": ["乐", "喜"]},
    "乐": {"synonyms": ["喜", "欢"], "antonyms": ["忧", "悲"]},
    "悲": {"synonyms": ["哀", "伤"], "antonyms": ["喜", "乐"]},
    "哀": {"synonyms": ["悲", "痛"], "antonyms": ["乐", "喜"]},
    "痛": {"synonyms": ["苦", "疼"], "antonyms": ["乐", "快"]},
    "苦": {"synonyms": ["痛", "辛"], "antonyms": ["甜", "甘"]},
    "辛": {"synonyms": ["苦", "辣"], "antonyms": ["甘", "甜"]},
    "甘": {"synonyms": ["甜"], "antonyms": ["苦", "辛"]},
    "欢": {"synonyms": ["喜", "乐"], "antonyms": ["悲", "愁"]},
    "愁": {"synonyms": ["忧", "烦"], "antonyms": ["欢", "乐"]},
    "烦": {"synonyms": ["恼", "厌"], "antonyms": ["舒", "爽"]},
    "恼": {"synonyms": ["怒", "烦"], "antonyms": ["喜", "悦"]},
    "悦": {"synonyms": ["喜", "欢"], "antonyms": ["恼", "怒"]},
    "舒": {"synonyms": ["畅", "适"], "antonyms": ["烦", "闷"]},
    "爽": {"synonyms": ["快", "舒"], "antonyms": ["闷", "烦"]},
    "闷": {"synonyms": ["烦", "郁"], "antonyms": ["爽", "舒"]},
    "郁": {"synonyms": ["闷", "愁"], "antonyms": ["畅", "舒"]},
    "畅": {"synonyms": ["舒", "顺"], "antonyms": ["阻", "闷"]},
    "适": {"synonyms": ["舒", "宜"], "antonyms": ["不适"]},

    # === 更多二字词对 ===
    "尊敬": {"synonyms": ["尊重", "敬重"], "antonyms": ["轻视", "蔑视"]},
    "轻视": {"synonyms": ["蔑视", "鄙视"], "antonyms": ["尊敬", "重视"]},
    "重视": {"synonyms": ["注重", "看重"], "antonyms": ["轻视", "忽视"]},
    "忽视": {"synonyms": ["忽略", "漠视"], "antonyms": ["重视", "关注"]},
    "关注": {"synonyms": ["关心", "留意"], "antonyms": ["忽视", "漠视"]},
    "漠视": {"synonyms": ["忽视", "无视"], "antonyms": ["关注", "重视"]},
    "欣赏": {"synonyms": ["赞赏", "鉴赏"], "antonyms": ["厌恶", "鄙视"]},
    "鄙视": {"synonyms": ["轻视", "蔑视"], "antonyms": ["尊重", "欣赏"]},
    "尊重": {"synonyms": ["尊敬", "敬重"], "antonyms": ["轻视", "侮辱"]},
    "侮辱": {"synonyms": ["羞辱", "辱骂"], "antonyms": ["尊重", "尊敬"]},
    "赞美": {"synonyms": ["歌颂", "颂扬"], "antonyms": ["诋毁", "贬低"]},
    "诋毁": {"synonyms": ["贬低", "毁谤"], "antonyms": ["赞美", "颂扬"]},
    "贬低": {"synonyms": ["诋毁", "轻视"], "antonyms": ["抬高", "赞美"]},
    "抬高": {"synonyms": ["提升", "拔高"], "antonyms": ["贬低", "压低"]},
    "压低": {"synonyms": ["降低"], "antonyms": ["抬高", "提升"]},
    "提升": {"synonyms": ["提高", "升高"], "antonyms": ["降低", "下降"]},
    "降低": {"synonyms": ["下降", "减低"], "antonyms": ["提升", "提高"]},
    "繁荣": {"synonyms": ["昌盛", "兴旺"], "antonyms": ["萧条", "衰败"]},
    "团结": {"synonyms": ["联合", "凝聚"], "antonyms": ["分裂", "涣散"]},
    "涣散": {"synonyms": ["松散", "散漫"], "antonyms": ["团结", "凝聚"]},
    "凝聚": {"synonyms": ["团结", "汇聚"], "antonyms": ["涣散", "分散"]},
    "汇聚": {"synonyms": ["聚集", "汇集"], "antonyms": ["分散", "散开"]},
    "分散": {"synonyms": ["散开", "分离"], "antonyms": ["汇聚", "聚集"]},
    "聚集": {"synonyms": ["集合", "汇聚"], "antonyms": ["分散", "散开"]},
    "集合": {"synonyms": ["聚集", "会合"], "antonyms": ["解散", "散开"]},
    "解散": {"synonyms": ["散开", "遣散"], "antonyms": ["集合", "聚集"]},
    "亲密": {"synonyms": ["亲近", "亲热"], "antonyms": ["疏远", "生疏"]},
    "疏远": {"synonyms": ["生疏", "远离"], "antonyms": ["亲密", "亲近"]},
    "生疏": {"synonyms": ["陌生", "疏远"], "antonyms": ["熟悉", "亲密"]},
    "熟悉": {"synonyms": ["熟识", "了解"], "antonyms": ["陌生", "生疏"]},
    "陌生": {"synonyms": ["生疏"], "antonyms": ["熟悉", "熟识"]},
    "了解": {"synonyms": ["明白", "知道"], "antonyms": ["误解", "不解"]},
    "误解": {"synonyms": ["曲解", "误会"], "antonyms": ["理解", "明白"]},
    "理解": {"synonyms": ["明白", "领悟"], "antonyms": ["误解", "困惑"]},
    "领悟": {"synonyms": ["体会", "领悟"], "antonyms": ["迷惑", "不解"]},
    "迷惑": {"synonyms": ["困惑", "不解"], "antonyms": ["领悟", "明白"]},
    "支持": {"synonyms": ["拥护", "支撑"], "antonyms": ["反对", "抵制"]},
    "拥护": {"synonyms": ["支持", "赞成"], "antonyms": ["反对", "抵制"]},
    "抵制": {"synonyms": ["反对", "抗拒"], "antonyms": ["支持", "拥护"]},
    "抗拒": {"synonyms": ["抵抗", "违抗"], "antonyms": ["服从", "顺从"]},
    "服从": {"synonyms": ["顺从", "听从"], "antonyms": ["抗拒", "违抗"]},
    "违抗": {"synonyms": ["抗拒", "反抗"], "antonyms": ["服从", "遵从"]},
    "遵从": {"synonyms": ["服从", "遵守"], "antonyms": ["违背", "违抗"]},
    "违背": {"synonyms": ["违反", "违抗"], "antonyms": ["遵从", "遵守"]},
    "遵守": {"synonyms": ["遵从", "恪守"], "antonyms": ["违反", "违背"]},
    "违反": {"synonyms": ["违背", "触犯"], "antonyms": ["遵守", "遵从"]},
    "创造": {"synonyms": ["发明", "创新"], "antonyms": ["模仿", "抄袭"]},
    "模仿": {"synonyms": ["仿造", "效仿"], "antonyms": ["创造", "创新"]},
    "创新": {"synonyms": ["革新", "变革"], "antonyms": ["守旧", "保守"]},
    "守旧": {"synonyms": ["保守", "墨守"], "antonyms": ["创新", "革新"]},
    "保守": {"synonyms": ["守旧", "传统"], "antonyms": ["开放", "进步"]},
    "开放": {"synonyms": ["开通", "开明"], "antonyms": ["保守", "封闭"]},
    "封闭": {"synonyms": ["关闭", "封锁"], "antonyms": ["开放", "开通"]},
    "开通": {"synonyms": ["开明", "开通"], "antonyms": ["保守", "顽固"]},
    "顽固": {"synonyms": ["固执", "执拗"], "antonyms": ["开明", "灵活"]},
    "固执": {"synonyms": ["顽固", "执拗"], "antonyms": ["灵活", "变通"]},
    "变通": {"synonyms": ["灵活", "通融"], "antonyms": ["死板", "固执"]},
    "死板": {"synonyms": ["呆板", "刻板"], "antonyms": ["灵活", "变通"]},
    "呆板": {"synonyms": ["死板", "木讷"], "antonyms": ["灵活", "生动"]},
    "生动": {"synonyms": ["活泼", "鲜活"], "antonyms": ["呆板", "死板"]},
    "活泼": {"synonyms": ["活跃", "灵动"], "antonyms": ["沉闷", "呆板"]},
    "沉闷": {"synonyms": ["压抑", "郁闷"], "antonyms": ["活泼", "活跃"]},
    "活跃": {"synonyms": ["活泼", "积极"], "antonyms": ["沉闷", "消沉"]},
    "孤独": {"synonyms": ["寂寞", "孤单"], "antonyms": ["热闹", "欢聚"]},
    "寂寞": {"synonyms": ["孤独", "孤单"], "antonyms": ["热闹", "欢聚"]},
    "孤单": {"synonyms": ["孤独", "寂寞"], "antonyms": ["团圆", "热闹"]},
    "团圆": {"synonyms": ["团聚", "欢聚"], "antonyms": ["分离", "离散"]},
    "分离": {"synonyms": ["分开", "离别"], "antonyms": ["团聚", "团圆"]},
    "团聚": {"synonyms": ["团圆", "欢聚"], "antonyms": ["分离", "离散"]},
    "离散": {"synonyms": ["分离", "散落"], "antonyms": ["团聚", "团圆"]},
    "欢聚": {"synonyms": ["团聚", "团圆"], "antonyms": ["离散", "分离"]},
    "欢喜": {"synonyms": ["高兴", "喜悦"], "antonyms": ["悲伤", "忧愁"]},
    "喜悦": {"synonyms": ["欢喜", "高兴"], "antonyms": ["悲伤", "忧愁"]},
    "忧愁": {"synonyms": ["忧闷", "忧心"], "antonyms": ["欢喜", "喜悦"]},
    "忧心": {"synonyms": ["担忧", "忧虑"], "antonyms": ["安心", "放心"]},
    "安心": {"synonyms": ["放心", "踏实"], "antonyms": ["忧心", "担忧"]},
    "踏实": {"synonyms": ["安心", "稳健"], "antonyms": ["浮躁", "飘浮"]},
    "浮躁": {"synonyms": ["急躁", "浮夸"], "antonyms": ["踏实", "沉稳"]},
    "沉稳": {"synonyms": ["稳重", "沉着"], "antonyms": ["浮躁", "轻浮"]},
    "轻浮": {"synonyms": ["浮夸", "轻佻"], "antonyms": ["沉稳", "稳重"]},
    "稳重": {"synonyms": ["沉稳", "老成"], "antonyms": ["轻浮", "浮躁"]},
    "老成": {"synonyms": ["稳重", "成熟"], "antonyms": ["幼稚", "轻浮"]},
    "幼稚": {"synonyms": ["天真", "稚嫩"], "antonyms": ["成熟", "老成"]},
    "成熟": {"synonyms": ["老练", "稳健"], "antonyms": ["幼稚", "稚嫩"]},
    "稚嫩": {"synonyms": ["幼嫩", "青涩"], "antonyms": ["成熟", "老练"]},
    "老练": {"synonyms": ["成熟", "干练"], "antonyms": ["稚嫩", "青涩"]},
    "青涩": {"synonyms": ["稚嫩", "生涩"], "antonyms": ["成熟", "老练"]},
    "干练": {"synonyms": ["老练", "精干"], "antonyms": ["无能", "笨拙"]},
    "精干": {"synonyms": ["干练", "精明"], "antonyms": ["笨拙", "无能"]},
    "精明": {"synonyms": ["聪明", "精干"], "antonyms": ["糊涂", "愚笨"]},
    "聪明": {"synonyms": ["机灵", "智慧"], "antonyms": ["愚笨", "糊涂"]},
    "愚笨": {"synonyms": ["愚蠢", "笨拙"], "antonyms": ["聪明", "灵巧"]},
    "笨拙": {"synonyms": ["愚笨", "迟钝"], "antonyms": ["灵巧", "敏捷"]},
    "灵巧": {"synonyms": ["敏捷", "灵活"], "antonyms": ["笨拙", "迟钝"]},
    "迟钝": {"synonyms": ["笨拙", "木讷"], "antonyms": ["敏捷", "灵敏"]},
    "灵敏": {"synonyms": ["敏捷", "机敏"], "antonyms": ["迟钝", "笨拙"]},
    "机敏": {"synonyms": ["机灵", "灵敏"], "antonyms": ["迟钝", "木讷"]},
    "木讷": {"synonyms": ["迟钝", "呆板"], "antonyms": ["机敏", "灵巧"]},

    # === 更多反义词对 ===
    "赞美": {"synonyms": ["颂扬", "夸奖"], "antonyms": ["贬损", "批评"]},
    "贬损": {"synonyms": ["贬低", "诋毁"], "antonyms": ["赞美", "夸奖"]},
    "表扬": {"synonyms": ["表彰", "嘉奖"], "antonyms": ["批评", "惩处"]},
    "惩处": {"synonyms": ["惩罚", "处分"], "antonyms": ["表扬", "嘉奖"]},
    "嘉奖": {"synonyms": ["表彰", "奖励"], "antonyms": ["惩处", "处罚"]},
    "表彰": {"synonyms": ["表扬", "嘉奖"], "antonyms": ["批评", "惩处"]},
    "宽容": {"synonyms": ["宽恕", "包容"], "antonyms": ["计较", "苛求"]},
    "计较": {"synonyms": ["苛求", "挑剔"], "antonyms": ["宽容", "包容"]},
    "包容": {"synonyms": ["宽容", "容纳"], "antonyms": ["排斥", "计较"]},
    "排斥": {"synonyms": ["排挤", "抵触"], "antonyms": ["包容", "接纳"]},
    "接纳": {"synonyms": ["接受", "接收"], "antonyms": ["排斥", "拒绝"]},
    "拒绝": {"synonyms": ["回绝", "推辞"], "antonyms": ["接纳", "接受"]},
    "推辞": {"synonyms": ["拒绝", "婉拒"], "antonyms": ["接受", "答应"]},
    "答应": {"synonyms": ["同意", "应允"], "antonyms": ["拒绝", "推辞"]},
    "应允": {"synonyms": ["答应", "允许"], "antonyms": ["拒绝", "回绝"]},
    "允许": {"synonyms": ["许可", "准许"], "antonyms": ["禁止", "不准"]},
    "禁止": {"synonyms": ["不准", "严禁"], "antonyms": ["允许", "许可"]},
    "许可": {"synonyms": ["允许", "准许"], "antonyms": ["禁止", "严禁"]},
    "准许": {"synonyms": ["允许", "许可"], "antonyms": ["禁止", "不准"]},
    "严禁": {"synonyms": ["禁止", "杜绝"], "antonyms": ["允许", "开放"]},
    "杜绝": {"synonyms": ["严禁", "禁止"], "antonyms": ["允许", "放任"]},
    "放任": {"synonyms": ["纵容", "放肆"], "antonyms": ["管束", "约束"]},
    "管束": {"synonyms": ["约束", "管教"], "antonyms": ["放任", "纵容"]},
    "约束": {"synonyms": ["管束", "限制"], "antonyms": ["放纵", "放任"]},
    "放纵": {"synonyms": ["放任", "纵容"], "antonyms": ["约束", "管束"]},
    "纵容": {"synonyms": ["放纵", "放任"], "antonyms": ["管束", "约束"]},

    # === 时间相关 ===
    "永恒": {"synonyms": ["永久", "永远"], "antonyms": ["短暂", "瞬间"]},
    "永远": {"synonyms": ["永恒", "永久"], "antonyms": ["暂时", "短暂"]},
    "瞬间": {"synonyms": ["刹那", "片刻"], "antonyms": ["永恒", "永远"]},
    "片刻": {"synonyms": ["瞬间", "须臾"], "antonyms": ["长久", "永恒"]},
    "须臾": {"synonyms": ["片刻", "瞬间"], "antonyms": ["长久", "漫长"]},
    "漫长": {"synonyms": ["长久", "遥远"], "antonyms": ["短暂", "瞬间"]},
    "遥远": {"synonyms": ["远", "辽远"], "antonyms": ["近", "附近"]},
    "附近": {"synonyms": ["近", "邻近"], "antonyms": ["遥远", "远方"]},
    "邻近": {"synonyms": ["附近", "相近"], "antonyms": ["遥远", "远方"]},

    # === 光线相关 ===
    "闪耀": {"synonyms": ["闪烁", "闪光"], "antonyms": ["暗淡", "昏暗"]},
    "闪烁": {"synonyms": ["闪耀", "闪动"], "antonyms": ["稳定", "恒定"]},
    "昏暗": {"synonyms": ["阴暗", "暗淡"], "antonyms": ["明亮", "光辉"]},
    "光辉": {"synonyms": ["光芒", "光彩"], "antonyms": ["暗淡", "昏暗"]},
    "光芒": {"synonyms": ["光辉", "光线"], "antonyms": ["黑暗", "阴影"]},
    "阴影": {"synonyms": ["暗影", "阴暗"], "antonyms": ["光明", "光辉"]},

    # === 更多数量相关 ===
    "充足": {"synonyms": ["充裕", "足够"], "antonyms": ["缺乏", "不足"]},
    "足够": {"synonyms": ["充足", "充裕"], "antonyms": ["不够", "缺乏"]},
    "不够": {"synonyms": ["不足", "缺乏"], "antonyms": ["足够", "充足"]},
    "丰富": {"synonyms": ["丰盛", "丰厚"], "antonyms": ["贫乏", "单调"]},
    "单调": {"synonyms": ["单一", "乏味"], "antonyms": ["丰富", "多样"]},
    "多样": {"synonyms": ["多元", "多种"], "antonyms": ["单一", "单调"]},
    "单一": {"synonyms": ["单调", "独一"], "antonyms": ["多样", "丰富"]},

    # === 动作对 ===
    "进攻": {"synonyms": ["攻击", "出击"], "antonyms": ["防守", "退守"]},
    "退守": {"synonyms": ["防守", "后撤"], "antonyms": ["进攻", "出击"]},
    "出击": {"synonyms": ["进攻", "出击"], "antonyms": ["防守", "固守"]},
    "固守": {"synonyms": ["坚守", "死守"], "antonyms": ["出击", "进攻"]},
    "死守": {"synonyms": ["固守", "坚守"], "antonyms": ["放弃", "撤退"]},
    "撤退": {"synonyms": ["退却", "后撤"], "antonyms": ["进攻", "前进"]},
    "前进": {"synonyms": ["前进", "迈进"], "antonyms": ["后退", "撤退"]},
    "后退": {"synonyms": ["倒退", "后撤"], "antonyms": ["前进", "迈进"]},
    "迈进": {"synonyms": ["前进", "跨步"], "antonyms": ["后退", "退缩"]},
    "退缩": {"synonyms": ["退却", "畏缩"], "antonyms": ["前进", "迈进"]},
    "畏缩": {"synonyms": ["退缩", "害怕"], "antonyms": ["勇敢", "前进"]},
    "勇猛": {"synonyms": ["英勇", "凶猛"], "antonyms": ["怯弱", "胆小"]},
    "怯弱": {"synonyms": ["胆小", "懦弱"], "antonyms": ["勇猛", "刚强"]},
    "懦弱": {"synonyms": ["怯弱", "软弱"], "antonyms": ["刚强", "勇敢"]},
    "刚强": {"synonyms": ["坚强", "刚毅"], "antonyms": ["懦弱", "软弱"]},
    "刚毅": {"synonyms": ["坚毅", "刚强"], "antonyms": ["懦弱", "软弱"]},
    "坚毅": {"synonyms": ["刚毅", "坚定"], "antonyms": ["动摇", "软弱"]},
    "坚定": {"synonyms": ["坚决", "坚毅"], "antonyms": ["动摇", "犹豫"]},
    "坚决": {"synonyms": ["坚定", "果断"], "antonyms": ["犹豫", "动摇"]},
    "果断": {"synonyms": ["坚决", "干脆"], "antonyms": ["犹豫", "优柔"]},
    "优柔": {"synonyms": ["犹豫", "寡断"], "antonyms": ["果断", "坚决"]},
    "寡断": {"synonyms": ["犹豫", "优柔"], "antonyms": ["果断", "决断"]},
    "决断": {"synonyms": ["果断", "决定"], "antonyms": ["犹豫", "寡断"]},
}

# 去除空列表、去重、确保没有自引用
cleaned = {}
for word, rels in raw_data.items():
    synonyms = list(set(s for s in rels.get("synonyms", []) if s != word))
    antonyms = list(set(a for a in rels.get("antonyms", []) if a != word))
    if synonyms or antonyms:  # 至少有一个关系才保留
        cleaned[word] = {
            "synonyms": synonyms,
            "antonyms": antonyms
        }

print(f"Total entries: {len(cleaned)}")

# Write to file
output_path = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'synonym_antonym.json')
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(cleaned, f, ensure_ascii=False, indent=2)

print(f"Written to {output_path}")
